/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.NhanVienDAO;
import Helper.DialogHelper;
import Helper.ShareHelper;
import Helper.UtilityHelper;
import Model.NhanVien;


/**
 *
 * @author DELL
 */
public class DoiMKJInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form doiMK
     */
    public DoiMKJInternal() {
        initComponents();
        init();
    }
    UtilityHelper util = new UtilityHelper();
    void init(){
        this.setTitle("Đổi mật khẩu");
        lblUser.setText(ShareHelper.USER.getMaNV());
    }
    NhanVien getmodel() {
        NhanVien model = ShareHelper.USER;
        model.setMatkhau(new String(TxtMKmoi.getPassword()));
        return model;
    }
    NhanVienDAO dao = new NhanVienDAO();
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtMkcu = new javax.swing.JPasswordField();
        TxtXacNhanMK = new javax.swing.JPasswordField();
        TxtMKmoi = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDoiMK = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Đổi Mật Khẩu");

        TxtMkcu.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        TxtXacNhanMK.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        TxtMKmoi.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu cũ");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu mới");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("xác nhận mật khẩu");

        btnDoiMK.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnDoiMK.setText("Đổi mật khẩu");
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUser.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(TxtMkcu)
                            .addComponent(TxtMKmoi)
                            .addComponent(TxtXacNhanMK, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnDoiMK)
                        .addGap(48, 48, 48)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblUser)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtMkcu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtMKmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtXacNhanMK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoiMK)
                    .addComponent(btnThoat))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        changePass();

    }//GEN-LAST:event_btnDoiMKActionPerformed
    
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed
    void changePass() {
        if(!util.checkNull(TxtMkcu, "Mật Khẩu cũ", this)){
            return;
        }
        if(!util.checkNull(TxtMKmoi, "Mật khẩu mới", this)){
            return;
        }
        if(!util.checkSokitu(TxtMKmoi,"Mật khẩu mới", 8, this )){
            return;
        }
        if(!util.checkNull(TxtXacNhanMK, "Xác nhận mật khẩu", this)){
            return;
        }
        NhanVien nv = ShareHelper.USER;
        String newpass = new String(TxtMKmoi.getPassword());
        String oldpass = new String(this.TxtMkcu.getPassword());
        String comfirm = new String(TxtXacNhanMK.getPassword());
        if (oldpass.equals(nv.getMatkhau())) {
            if (newpass.equals(comfirm)) {
                try {
                    dao.update(this.getmodel());
                    DialogHelper.alert(this, "Đổi mật khẩu thành công \n"
                            + "Bạn cần đăng nhập lại tài khoản với mật khẩu mới");
                    ShareHelper.USER = null;
                    this.dispose();
                } catch (Exception e) {
                    DialogHelper.alert(this, "Đổi mật khẩu không thành công");
                }
            } else {
                DialogHelper.alert(this, "Xác nhận mật khẩu chưa đúng");
            }
        } else {
            DialogHelper.alert(this, "Mật khẩu chưa đúng");
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TxtMKmoi;
    private javax.swing.JPasswordField TxtMkcu;
    private javax.swing.JPasswordField TxtXacNhanMK;
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
