/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.KhachHangDAO;
import Helper.DialogHelper;
import Helper.ShareHelper;
import Helper.UtilityHelper;
import Model.KhachHang;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class KhachHangFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form KhachHangFrame
     */
    public KhachHangFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtDiaChiKH = new javax.swing.JTextField();
        lblSDT2 = new javax.swing.JLabel();
        lblEmail2 = new javax.swing.JLabel();
        lblMaNV1 = new javax.swing.JLabel();
        txtTimKiemKH = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblTenNV1 = new javax.swing.JLabel();
        btnTimKiemKH = new javax.swing.JButton();
        txtTenKH = new javax.swing.JTextField();
        lblEmail3 = new javax.swing.JLabel();
        txtSDTKH = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtGhiChuKH = new javax.swing.JTextArea();
        lblSDT1 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        lblVaiTro1 = new javax.swing.JLabel();
        btnPrevKH = new javax.swing.JButton();
        txtEmailKH = new javax.swing.JTextField();
        btnFirstKH = new javax.swing.JButton();
        btnLastKH = new javax.swing.JButton();
        btnThemKH = new javax.swing.JButton();
        btnNextKH = new javax.swing.JButton();
        btnCapNhatKH = new javax.swing.JButton();
        btnXoaKh = new javax.swing.JButton();
        btnClearKH = new javax.swing.JButton();
        rdoNamKH = new javax.swing.JRadioButton();
        rdoNuKH = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblKhachHang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtLoai = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Quản Lý Khách Hàng");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        txtDiaChiKH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblSDT2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSDT2.setText("Địa chỉ");

        lblEmail2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEmail2.setText("Xếp Hạng");

        lblMaNV1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMaNV1.setText("Mã Khách Hàng");

        txtTimKiemKH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtMaKH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKHActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Tên khách hàng");

        lblTenNV1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTenNV1.setText(" Tên Khách hàng");

        btnTimKiemKH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTimKiemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Zoom.png"))); // NOI18N
        btnTimKiemKH.setText("Tìm kiếm");
        btnTimKiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemKHActionPerformed(evt);
            }
        });

        txtTenKH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });

        lblEmail3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEmail3.setText("Ghi chú");

        txtSDTKH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtGhiChuKH.setColumns(20);
        txtGhiChuKH.setRows(5);
        jScrollPane3.setViewportView(txtGhiChuKH);

        lblSDT1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSDT1.setText("Số Điện Thoại");

        lblEmail1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEmail1.setText("Email");

        lblVaiTro1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblVaiTro1.setText("Giới tính");

        btnPrevKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/prev.png"))); // NOI18N
        btnPrevKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevKHActionPerformed(evt);
            }
        });

        txtEmailKH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnFirstKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1.png"))); // NOI18N
        btnFirstKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstKHActionPerformed(evt);
            }
        });

        btnLastKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2.png"))); // NOI18N
        btnLastKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastKHActionPerformed(evt);
            }
        });

        btnThemKH.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Accept.png"))); // NOI18N
        btnThemKH.setText("Thêm");
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });

        btnNextKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        btnNextKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextKHActionPerformed(evt);
            }
        });

        btnCapNhatKH.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCapNhatKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Upload.png"))); // NOI18N
        btnCapNhatKH.setText("Cập Nhật");
        btnCapNhatKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatKHActionPerformed(evt);
            }
        });

        btnXoaKh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnXoaKh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoaKh.setText("Xóa");
        btnXoaKh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKhActionPerformed(evt);
            }
        });

        btnClearKH.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnClearKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnClearKH.setText("Mới");
        btnClearKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearKHActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNamKH);
        rdoNamKH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdoNamKH.setText("Nam");

        buttonGroup1.add(rdoNuKH);
        rdoNuKH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdoNuKH.setText("Nữ");
        rdoNuKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuKHActionPerformed(evt);
            }
        });

        TblKhachHang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khach Hàng", "Tên Khách Hàng", "Giới Tính", "Địa chỉ", "Số điện thoại", "Email", "Xếp Hạng", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblKhachHang);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Quản Lý Khách Hàng");

        txtLoai.setBackground(new java.awt.Color(204, 204, 204));
        txtLoai.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(btnTimKiemKH))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblMaNV1)
                                                .addComponent(lblSDT1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblSDT2, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(lblVaiTro1))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdoNamKH)
                                                .addGap(47, 47, 47)
                                                .addComponent(rdoNuKH))
                                            .addComponent(txtMaKH)
                                            .addComponent(txtSDTKH)
                                            .addComponent(txtDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(145, 145, 145)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTenNV1)
                                            .addComponent(lblEmail1)
                                            .addComponent(lblEmail2)
                                            .addComponent(lblEmail3))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTenKH)
                                            .addComponent(txtEmailKH)
                                            .addComponent(jScrollPane3)
                                            .addComponent(txtLoai)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(248, 248, 248)
                                        .addComponent(btnFirstKH)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPrevKH)
                                        .addGap(159, 159, 159)
                                        .addComponent(btnNextKH)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLastKH))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(btnThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnCapNhatKH)
                                .addGap(50, 50, 50)
                                .addComponent(btnXoaKh, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btnClearKH, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnTimKiemKH)
                    .addComponent(txtTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnNextKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLastKH))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnPrevKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFirstKH)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenNV1)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaNV1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail1)
                            .addComponent(txtSDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSDT1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail2)
                            .addComponent(txtDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSDT2)
                            .addComponent(txtLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVaiTro1)
                        .addComponent(rdoNamKH)
                        .addComponent(rdoNuKH)
                        .addComponent(lblEmail3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKH)
                    .addComponent(btnCapNhatKH)
                    .addComponent(btnXoaKh)
                    .addComponent(btnClearKH))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKHActionPerformed

    private void btnTimKiemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemKHActionPerformed
        loadDBFromKH();
        if(!ShareHelper.USER.isVaitro()){
            btnXoaKh.setEnabled(false);
        }
    }//GEN-LAST:event_btnTimKiemKHActionPerformed

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void btnPrevKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevKHActionPerformed
        indexKH--;
        this.editDisplayKH();
    }//GEN-LAST:event_btnPrevKHActionPerformed

    private void btnFirstKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstKHActionPerformed
        indexKH = 0;
        this.editDisplayKH();
    }//GEN-LAST:event_btnFirstKHActionPerformed

    private void btnLastKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastKHActionPerformed
        indexKH = TblKhachHang.getRowCount() - 1;
        this.editDisplayKH();
    }//GEN-LAST:event_btnLastKHActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
         insertDBFromKH();
        loadDBFromKH();
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void btnNextKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextKHActionPerformed
        indexKH++;
        this.editDisplayKH();
    }//GEN-LAST:event_btnNextKHActionPerformed

    private void btnCapNhatKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatKHActionPerformed
        updateDBFromKH();
        loadDBFromKH();
    }//GEN-LAST:event_btnCapNhatKHActionPerformed

    private void btnXoaKhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhActionPerformed
        deleteDBFromKH();
        loadDBFromKH();
    }//GEN-LAST:event_btnXoaKhActionPerformed

    private void btnClearKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearKHActionPerformed
        clearModelKH();
    }//GEN-LAST:event_btnClearKHActionPerformed

    private void rdoNuKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNuKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNuKHActionPerformed

    private void TblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblKhachHangMouseClicked
        if (evt.getClickCount() == 2) {
            indexKH = TblKhachHang.getSelectedRow();
            this.editDisplayKH();
            this.setStatusFormKH(false);
            if(!ShareHelper.USER.isVaitro()){
            btnXoaKh.setEnabled(false);
        }
        }
    }//GEN-LAST:event_TblKhachHangMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        loadDBFromKH();
        setStatusFormKH(true);
        if(!ShareHelper.USER.isVaitro()){
            btnXoaKh.setEnabled(false);
        }
    }//GEN-LAST:event_formInternalFrameOpened

     int indexKH;
    KhachHangDAO khdao = new KhachHangDAO();

    void loadDBFromKH() {
        DefaultTableModel model = (DefaultTableModel) TblKhachHang.getModel();
        model.setRowCount(0);
        try {
            String tenKh = txtTimKiemKH.getText();
            List<KhachHang> list = khdao.selectByKeyword(tenKh);

            for (KhachHang kh : list) {

                Object[] row = {
                    kh.getMaKH(), kh.getTenKH(), kh.isGioitinh() ? "Nam" : "Nữ", kh.getDiachi(),
                    kh.getSdt(), kh.getEmail(), util.getRank(kh.getLoai()), kh.getGhichu()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    void insertDBFromKH() {
        if(!util.checkMaKH(txtMaKH, this)){
            DialogHelper.alert(this, "Khách hàng đã tồn tại");
            return;
        }
         if(!util.checkNull(txtMaKH,"Mã khách hàng", this)){
            return;
        }
        if(!check()){
            return;
        }
        KhachHang model = getModelKH();
        try {
            khdao.insert(model);
            this.loadDBFromKH();
            this.clearModelKH();
            DialogHelper.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Thêm mới thất bại" + e);
        }
    }

    void updateDBFromKH() {
        if(!check()){
            return;
        }
        KhachHang model = getModelKH();
        try {
            khdao.update(model);
            this.loadDBFromKH();
            this.clearModelKH();
            DialogHelper.alert(this, "Cập nhật thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại");
        }
    }

    void deleteDBFromKH() {
         if(!util.checkLicense(this)){
           return;
       }

        if (DialogHelper.confirm(this, "Bạn thực sự muốn xóa Khách hàng này?")) {
            String makh = txtMaKH.getText();
            try {
                khdao.delete(makh);
                this.loadDBFromKH();
                this.clearModelKH();
                DialogHelper.alert(this, "Xóa thành công!");
            } catch (Exception e) {
                DialogHelper.alert(this, "Xóa thất bại!");
            }
        }
    }

    void editDisplayKH() {
        try {
            String makh = (String) TblKhachHang.getValueAt(this.indexKH, 0);
            KhachHang model = khdao.findById(makh);
            if (model != null) {
                this.setModelKH(model);
                this.setStatusFormKH(false);
                TblKhachHang.setRowSelectionInterval(indexKH, indexKH);
            }
            if(!ShareHelper.USER.isVaitro()){
            btnXoaKh.setEnabled(false);
        }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void clearModelKH() {
        this.setModelKH(new KhachHang());
        this.setStatusFormKH(true);
        if(!ShareHelper.USER.isVaitro()){
            btnXoaKh.setEnabled(false);
        }
    }

    void setModelKH(KhachHang model) {
        txtMaKH.setText(model.getMaKH());
        txtTenKH.setText(model.getTenKH());
        rdoNamKH.setSelected(model.isGioitinh());
        rdoNuKH.setSelected(!model.isGioitinh());
        txtDiaChiKH.setText(model.getDiachi());
        txtSDTKH.setText(model.getSdt());
        txtEmailKH.setText(model.getEmail());
        txtLoai.setText(util.getRank(model.getLoai()));
        txtGhiChuKH.setText(model.getGhichu());
    }

    KhachHang getModelKH() {
        KhachHang model = new KhachHang();
        model.setMaKH(txtMaKH.getText());
        model.setTenKH(txtTenKH.getText());
        model.setGioitinh(rdoNamKH.isSelected());
        model.setDiachi(txtDiaChiKH.getText());
        model.setSdt(txtSDTKH.getText());
        model.setEmail(txtEmailKH.getText());
        model.setLoai(util.setRank(txtLoai.getText()));
        model.setGhichu(txtGhiChuKH.getText());
        return model;
    }

    void setStatusFormKH(boolean insertable) {
        txtMaKH.setEditable(insertable);
        btnThemKH.setEnabled(insertable);
        btnCapNhatKH.setEnabled(!insertable);
        btnXoaKh.setEnabled(!insertable);

        boolean first = this.indexKH > 0;
        boolean last = this.indexKH < TblKhachHang.getRowCount() - 1;
        btnFirstKH.setEnabled(!insertable && first);
        btnPrevKH.setEnabled(!insertable && first);
        btnNextKH.setEnabled(!insertable && last);
        btnLastKH.setEnabled(!insertable && last);
    }
    UtilityHelper util = new UtilityHelper();
    boolean check(){
        if(!util.checkNull(txtTenKH, "Tên Khách Hàng", this)){
            return false;
        }
       
        if(!util.checkName(txtTenKH, this)){
            return false;
        }
         if(!util.checkNull(txtSDTKH, "SDT Khách Hàng", this)){
            return false;
        }
         
          if(!util.checkPhone(txtSDTKH, this)){
            return false;
        }
          
           if(!util.checkNull(txtEmailKH, "Email Khách Hàng", this)){
            return false;
        }
            if(!util.checkEmail(txtEmailKH, this)){
            return false;
        }
             if(!util.checkNull(txtDiaChiKH, "Địa chỉ Khách Hàng", this)){
            return false;
        }
              if(!util.checkNull(txtDiaChiKH,"Địa chỉ", this)){
            return false;
        }
         return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblKhachHang;
    private javax.swing.JButton btnCapNhatKH;
    private javax.swing.JButton btnClearKH;
    private javax.swing.JButton btnFirstKH;
    private javax.swing.JButton btnLastKH;
    private javax.swing.JButton btnNextKH;
    private javax.swing.JButton btnPrevKH;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnTimKiemKH;
    private javax.swing.JButton btnXoaKh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEmail3;
    private javax.swing.JLabel lblMaNV1;
    private javax.swing.JLabel lblSDT1;
    private javax.swing.JLabel lblSDT2;
    private javax.swing.JLabel lblTenNV1;
    private javax.swing.JLabel lblVaiTro1;
    private javax.swing.JRadioButton rdoNamKH;
    private javax.swing.JRadioButton rdoNuKH;
    private javax.swing.JTextField txtDiaChiKH;
    private javax.swing.JTextField txtEmailKH;
    private javax.swing.JTextArea txtGhiChuKH;
    private javax.swing.JTextField txtLoai;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDTKH;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKiemKH;
    // End of variables declaration//GEN-END:variables
}
