/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Helper.DialogHelper;
import Helper.ShareHelper;
import Helper.UtilityHelper;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author DELL
 */
public class MainframeShop extends javax.swing.JFrame {

    /**
     * Creates new form MainframeShop
     */
    public MainframeShop() {
        initComponents();
        init();
    }
    UtilityHelper util = new UtilityHelper();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane(){protected void  paintComponent (Graphics g){
            Image img = new ImageIcon(this.getClass().getResource("/images/mau-logo-dep.jpg")).getImage();
            try {
                Graphics g2d = (Graphics2D)g;
                double x= img.getWidth(null);
                double y= img.getHeight(null);

                g2d.drawImage(img, this.getWidth()/4+200,this.getHeight()/4,this);
            } catch (Exception e) {
                System.out.println("Gap loi");
            }}};
            jPanel1 = new javax.swing.JPanel();
            btnHoadon = new javax.swing.JButton();
            btnSanPham = new javax.swing.JButton();
            btnKhachHang = new javax.swing.JButton();
            btnPhieuNhap = new javax.swing.JButton();
            btnNhanVien = new javax.swing.JButton();
            btnThongke = new javax.swing.JButton();
            jPanel2 = new javax.swing.JPanel();
            displayTenNV = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            btnDangNhap = new javax.swing.JButton();
            btnExit = new javax.swing.JButton();
            jMenuBar1 = new javax.swing.JMenuBar();
            mnLogout = new javax.swing.JMenu();
            jMenuItem10 = new javax.swing.JMenuItem();
            mnDoiMK = new javax.swing.JMenuItem();
            jSeparator1 = new javax.swing.JPopupMenu.Separator();
            jSeparator2 = new javax.swing.JPopupMenu.Separator();
            mnExit = new javax.swing.JMenuItem();
            jMenu2 = new javax.swing.JMenu();
            mnPhieuNhap = new javax.swing.JMenuItem();
            mnNhanVien = new javax.swing.JMenuItem();
            jMenu3 = new javax.swing.JMenu();
            mnHoaDon = new javax.swing.JMenuItem();
            mnSanPham = new javax.swing.JMenuItem();
            mnKhachHang = new javax.swing.JMenuItem();
            jMenu4 = new javax.swing.JMenu();
            mnNhapHang = new javax.swing.JMenuItem();
            mnBanHang = new javax.swing.JMenuItem();

            jMenuItem1.setText("jMenuItem1");

            jMenuItem2.setText("jMenuItem2");

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

            jPanel1.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.setLayout(new java.awt.GridLayout(0, 1));

            btnHoadon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            btnHoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoadon.png"))); // NOI18N
            btnHoadon.setText("Tạo Hóa Đơn");
            btnHoadon.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
            btnHoadon.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnHoadonActionPerformed(evt);
                }
            });
            jPanel1.add(btnHoadon);

            btnSanPham.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sanpham.png"))); // NOI18N
            btnSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
            btnSanPham.setLabel("Quản Lý Sản Phẩm");
            btnSanPham.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSanPhamActionPerformed(evt);
                }
            });
            jPanel1.add(btnSanPham);

            btnKhachHang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/khachHang.png"))); // NOI18N
            btnKhachHang.setText("Quản lý Khách Hàng");
            btnKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
            btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnKhachHangActionPerformed(evt);
                }
            });
            jPanel1.add(btnKhachHang);

            btnPhieuNhap.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            btnPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doitac.png"))); // NOI18N
            btnPhieuNhap.setText("Tạo Phiếu Nhập");
            btnPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
            btnPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnPhieuNhapActionPerformed(evt);
                }
            });
            jPanel1.add(btnPhieuNhap);

            btnNhanVien.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nhanvien.png"))); // NOI18N
            btnNhanVien.setText("Quản Lý Nhân Viên");
            btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
            btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnNhanVienActionPerformed(evt);
                }
            });
            jPanel1.add(btnNhanVien);

            btnThongke.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doanhthu.png"))); // NOI18N
            btnThongke.setText("Thống Kê");
            btnThongke.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
            btnThongke.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnThongkeActionPerformed(evt);
                }
            });
            jPanel1.add(btnThongke);

            jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

            displayTenNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
            displayTenNV.setText("[Tên Nhân Viên]");

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-9.png"))); // NOI18N

            btnDangNhap.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
            btnDangNhap.setText("Đăng Xuất");
            btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnDangNhapActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(displayTenNV)
                        .addComponent(btnDangNhap))
                    .addGap(18, 18, 18))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(btnDangNhap)
                    .addGap(18, 18, 18)
                    .addComponent(displayTenNV)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thoat.png"))); // NOI18N
            btnExit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnExitActionPerformed(evt);
                }
            });

            jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
            jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
            jDesktopPane1.setLayer(btnExit, javax.swing.JLayeredPane.DEFAULT_LAYER);

            javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
            jDesktopPane1.setLayout(jDesktopPane1Layout);
            jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 805, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnExit)
                    .addGap(19, 19, 19))
            );
            jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );

            mnLogout.setText("Hệ Thống");

            jMenuItem10.setText("Đăng Xuất");
            jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem10ActionPerformed(evt);
                }
            });
            mnLogout.add(jMenuItem10);

            mnDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
            mnDoiMK.setText("Đổi Mật Khẩu");
            mnDoiMK.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnDoiMKActionPerformed(evt);
                }
            });
            mnLogout.add(mnDoiMK);
            mnLogout.add(jSeparator1);
            mnLogout.add(jSeparator2);

            mnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
            mnExit.setText("Thoát");
            mnExit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnExitActionPerformed(evt);
                }
            });
            mnLogout.add(mnExit);

            jMenuBar1.add(mnLogout);

            jMenu2.setText("Quản lý");

            mnPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Notes.png"))); // NOI18N
            mnPhieuNhap.setText("Tạo Phiếu Nhập");
            mnPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnPhieuNhapActionPerformed(evt);
                }
            });
            jMenu2.add(mnPhieuNhap);

            mnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Boy.png"))); // NOI18N
            mnNhanVien.setText("Quản Lý Nhân Viên");
            mnNhanVien.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnNhanVienActionPerformed(evt);
                }
            });
            jMenu2.add(mnNhanVien);

            jMenuBar1.add(jMenu2);

            jMenu3.setText("Bán hàng");

            mnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Remove from basket.png"))); // NOI18N
            mnHoaDon.setText("Tạo Hóa Đơn");
            mnHoaDon.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnHoaDonActionPerformed(evt);
                }
            });
            jMenu3.add(mnHoaDon);

            mnSanPham.setText("Sản Phẩm");
            mnSanPham.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnSanPhamActionPerformed(evt);
                }
            });
            jMenu3.add(mnSanPham);

            mnKhachHang.setText("Khách Hàng");
            mnKhachHang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnKhachHangActionPerformed(evt);
                }
            });
            jMenu3.add(mnKhachHang);

            jMenuBar1.add(jMenu3);

            jMenu4.setText("Thống kê");

            mnNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Bar chart.png"))); // NOI18N
            mnNhapHang.setText("Nhập Hàng");
            mnNhapHang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnNhapHangActionPerformed(evt);
                }
            });
            jMenu4.add(mnNhapHang);

            mnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Coin.png"))); // NOI18N
            mnBanHang.setText("Doanh thu");
            mnBanHang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnBanHangActionPerformed(evt);
                }
            });
            jMenu4.add(mnBanHang);

            jMenuBar1.add(jMenu4);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktopPane1)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void mnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNhapHangActionPerformed
        openThongke(0);
    }//GEN-LAST:event_mnNhapHangActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:

        Logout();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void mnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSanPhamActionPerformed
        openSanPham();
    }//GEN-LAST:event_mnSanPhamActionPerformed

    private void mnPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPhieuNhapActionPerformed
        openPhieuNhap();
    }//GEN-LAST:event_mnPhieuNhapActionPerformed

    private void btnPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuNhapActionPerformed
        openPhieuNhap();
    }//GEN-LAST:event_btnPhieuNhapActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        openNhanvien();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        openKhachHang();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoadonActionPerformed
        openHoaDon();
    }//GEN-LAST:event_btnHoadonActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        openSanPham();
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        openThongke(0);
    }//GEN-LAST:event_btnThongkeActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Logout();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void mnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDoiMKActionPerformed
        openDoiMK();
    }//GEN-LAST:event_mnDoiMKActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        exit();
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNhanVienActionPerformed
        openNhanvien();
    }//GEN-LAST:event_mnNhanVienActionPerformed

    private void mnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHoaDonActionPerformed
        openHoaDon();
    }//GEN-LAST:event_mnHoaDonActionPerformed

    private void mnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKhachHangActionPerformed
        openKhachHang();
    }//GEN-LAST:event_mnKhachHangActionPerformed

    private void mnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBanHangActionPerformed
        openThongke(1);
    }//GEN-LAST:event_mnBanHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainframeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainframeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainframeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainframeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainframeShop().setVisible(true);
            }
        });
    }
    
    void init() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Shop Rosez");
        openLogin();
    }
    
    void Logout() {
        if (DialogHelper.confirm(this, "Bạn có muốn đăng xuất")) {
            ShareHelper.USER = null;
            openLogin();
        }
        
    }
    
    void exit() {
        if (DialogHelper.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?")) {
            System.exit(0);
        }
    }
    
    void openLogin() {
        for (JInternalFrame frm : jDesktopPane1.getAllFrames()) {
            frm.dispose();
        }
        new DangNhapJDialog(this, rootPaneCheckingEnabled).setVisible(true);
        
        displayTenNV.setText(ShareHelper.USER.getTenNV());
        if (!ShareHelper.USER.isVaitro()) {
            btnThongke.setEnabled(false);
            btnNhanVien.setEnabled(false);
            btnPhieuNhap.setEnabled(false);
        } else {
            btnThongke.setEnabled(true);
            btnNhanVien.setEnabled(true);
            btnPhieuNhap.setEnabled(true);
        }
    }
    
    void openPhieuNhap() {
//         if(!util.checkLicense(this)){
//           return;
//       }
        if (ShareHelper.authenticated()) {
            for (JInternalFrame frm : jDesktopPane1.getAllFrames()) {
                frm.dispose();
            }
            PhieuNhapFrame phieunhapj = new PhieuNhapFrame();
            jDesktopPane1.add(phieunhapj);
            phieunhapj.setLocation(this.getWidth() / 2 - phieunhapj.getWidth() / 2, this.getHeight() / 2 - phieunhapj.getHeight() / 2);
            phieunhapj.setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }
    
    void openThongke(int i) {
//       if(!util.checkLicense(this)){
//           return;
//       }
        if (ShareHelper.authenticated()) {
            for (JInternalFrame frm : jDesktopPane1.getAllFrames()) {
                frm.dispose();
            }
            Thongkeform frame = new Thongkeform(i);
            jDesktopPane1.add(frame);
            frame.setLocation(this.getWidth() / 2 - frame.getWidth() / 2, this.getHeight() / 2 - frame.getHeight() / 2);
            frame.setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }
    
    void openKhachHang() {
        
        if (ShareHelper.authenticated()) {
            for (JInternalFrame frm : jDesktopPane1.getAllFrames()) {
                frm.dispose();
            }
            KhachHangFrame frame = new KhachHangFrame();
            jDesktopPane1.add(frame);
            frame.setLocation(this.getWidth() / 2 - frame.getWidth() / 2, this.getHeight() / 2 - frame.getHeight() / 2);
            frame.setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
        
    }
    
    void openSanPham() {
        
        if (ShareHelper.authenticated()) {
            for (JInternalFrame frm : jDesktopPane1.getAllFrames()) {
                frm.dispose();
            }
            SanPhamFrame frame = new SanPhamFrame();
            jDesktopPane1.add(frame);
            frame.setLocation(this.getWidth() / 2 - frame.getWidth() / 2, this.getHeight() / 2 - frame.getHeight() / 2);
            frame.setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
        
    }
    
    void openNhanvien() {
//        if(!util.checkLicense(this)){
//           return;
//       }
        if (ShareHelper.authenticated()) {
            for (JInternalFrame frm : jDesktopPane1.getAllFrames()) {
                frm.dispose();
            }
            NhanVienFrame frame = new NhanVienFrame();
            jDesktopPane1.add(frame);
            frame.setLocation(this.getWidth() / 2 - frame.getWidth() / 2, this.getHeight() / 2 - frame.getHeight() / 2);
            frame.setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
        
    }
    
    void openHoaDon() {
        
        if (ShareHelper.authenticated()) {
            for (JInternalFrame frm : jDesktopPane1.getAllFrames()) {
                frm.dispose();
            }
            HoaDonJInternalFrame frame = new HoaDonJInternalFrame();
            jDesktopPane1.add(frame);
            frame.setLocation(this.getWidth() / 2 - frame.getWidth() / 2, this.getHeight() / 2 - frame.getHeight() / 2);
            frame.setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
        
    }
    
    void openDoiMK() {
        if (ShareHelper.authenticated()) {
            for (JInternalFrame frm : jDesktopPane1.getAllFrames()) {
                frm.dispose();
            }
            DoiMKJInternal frame = new DoiMKJInternal();
            jDesktopPane1.add(frame);
            frame.setLocation(this.getWidth() / 2 - frame.getWidth() / 2, this.getHeight() / 2 - frame.getHeight() / 2);
            frame.setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHoadon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhieuNhap;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThongke;
    private javax.swing.JLabel displayTenNV;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnBanHang;
    private javax.swing.JMenuItem mnDoiMK;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnHoaDon;
    private javax.swing.JMenuItem mnKhachHang;
    private javax.swing.JMenu mnLogout;
    private javax.swing.JMenuItem mnNhanVien;
    private javax.swing.JMenuItem mnNhapHang;
    private javax.swing.JMenuItem mnPhieuNhap;
    private javax.swing.JMenuItem mnSanPham;
    // End of variables declaration//GEN-END:variables
}
