/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.NhanVienDAO;
import Helper.DialogHelper;
import Helper.ShareHelper;
import Helper.UtilityHelper;
import Model.NhanVien;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class NhanVienFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form NhanVienFrame
     */
    public NhanVienFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtTenNV = new javax.swing.JTextField();
        btnClearNV = new javax.swing.JButton();
        txtSDTNV = new javax.swing.JTextField();
        rdoQuanLy = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnPrevNV = new javax.swing.JButton();
        btnFirstNV = new javax.swing.JButton();
        lblSDT = new javax.swing.JLabel();
        btnLastNV = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        btnNextNV = new javax.swing.JButton();
        lblVaiTro = new javax.swing.JLabel();
        lblMK = new javax.swing.JLabel();
        txtEmailNV = new javax.swing.JTextField();
        txtPassNV = new javax.swing.JPasswordField();
        lblMaNV = new javax.swing.JLabel();
        btnThemNV = new javax.swing.JButton();
        txtMaNV = new javax.swing.JTextField();
        btnCapNhatNV = new javax.swing.JButton();
        lblTenNV = new javax.swing.JLabel();
        btnXoaNV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtXacNhanMK = new javax.swing.JPasswordField();
        btnmokhoa = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Quản Lý Nhân Viên");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        txtTenNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });

        btnClearNV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnClearNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnClearNV.setText("Mới");
        btnClearNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearNVActionPerformed(evt);
            }
        });

        txtSDTNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        buttonGroup1.add(rdoQuanLy);
        rdoQuanLy.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdoQuanLy.setSelected(true);
        rdoQuanLy.setText("Quản lý");

        buttonGroup1.add(rdoNhanVien);
        rdoNhanVien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdoNhanVien.setText("Nhân Viên");
        rdoNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNhanVienActionPerformed(evt);
            }
        });

        tblNhanVien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "SĐT", "Email", "Vai Trò", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        btnPrevNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/prev.png"))); // NOI18N
        btnPrevNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevNVActionPerformed(evt);
            }
        });

        btnFirstNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1.png"))); // NOI18N
        btnFirstNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstNVActionPerformed(evt);
            }
        });

        lblSDT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSDT.setText("Số Điện Thoại");

        btnLastNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2.png"))); // NOI18N
        btnLastNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastNVActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEmail.setText("Email");

        btnNextNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        btnNextNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextNVActionPerformed(evt);
            }
        });

        lblVaiTro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblVaiTro.setText("Vai Trò");

        lblMK.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMK.setText("Mật Khẩu");

        txtEmailNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtPassNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblMaNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMaNV.setText("Mã Nhân Viên");

        btnThemNV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnThemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Accept.png"))); // NOI18N
        btnThemNV.setText("Thêm");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        txtMaNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        btnCapNhatNV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCapNhatNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Upload.png"))); // NOI18N
        btnCapNhatNV.setText("Cập Nhật");
        btnCapNhatNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatNVActionPerformed(evt);
            }
        });

        lblTenNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTenNV.setText("Tên Nhân Viên");

        btnXoaNV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnXoaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoaNV.setText("Xóa");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Quản Lý Nhân Viên");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Xác Nhận MK");

        txtXacNhanMK.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnmokhoa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnmokhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tick.png"))); // NOI18N
        btnmokhoa.setText("Mở Khóa");
        btnmokhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmokhoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(289, 289, 289)
                                        .addComponent(btnFirstNV)
                                        .addGap(47, 47, 47)
                                        .addComponent(btnPrevNV))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMaNV)
                                            .addComponent(lblSDT)
                                            .addComponent(lblMK)
                                            .addComponent(jLabel2))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPassNV, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtSDTNV, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                            .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                            .addComponent(txtXacNhanMK))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNextNV)
                                .addGap(53, 53, 53)
                                .addComponent(btnLastNV))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenNV)
                                    .addComponent(lblVaiTro)
                                    .addComponent(lblEmail)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTenNV)
                                            .addComponent(txtEmailNV)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdoQuanLy)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                                .addComponent(rdoNhanVien))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(btnClearNV, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnCapNhatNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnmokhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPrevNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNextNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLastNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFirstNV))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNV)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenNV)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSDT)
                            .addComponent(txtSDTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVaiTro)
                            .addComponent(rdoQuanLy)
                            .addComponent(rdoNhanVien)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMK)
                            .addComponent(txtPassNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtXacNhanMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhatNV)
                    .addComponent(btnThemNV)
                    .addComponent(btnXoaNV)
                    .addComponent(btnClearNV)
                    .addComponent(btnmokhoa))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed

    private void btnClearNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearNVActionPerformed
        // TODO add your handling code here:
        this.clearModelNV();
    }//GEN-LAST:event_btnClearNVActionPerformed

    private void rdoNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNhanVienActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.indexNV = tblNhanVien.rowAtPoint(evt.getPoint());
            if (this.indexNV >= 0) {
                this.editDisplayNV();

            }
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnPrevNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevNVActionPerformed
        // TODO add your handling code here:
        this.indexNV--;
        this.editDisplayNV();
    }//GEN-LAST:event_btnPrevNVActionPerformed

    private void btnFirstNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstNVActionPerformed
        // TODO add your handling code here:
        this.indexNV = 0;
        this.editDisplayNV();
    }//GEN-LAST:event_btnFirstNVActionPerformed

    private void btnLastNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastNVActionPerformed
        // TODO add your handling code here:
        this.indexNV = tblNhanVien.getRowCount() - 1;
        this.editDisplayNV();
    }//GEN-LAST:event_btnLastNVActionPerformed

    private void btnNextNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextNVActionPerformed
        // TODO add your handling code here:
        this.indexNV++;
        this.editDisplayNV();
    }//GEN-LAST:event_btnNextNVActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        // TODO add your handling code here:
        this.insertDBFromNV();
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void btnCapNhatNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatNVActionPerformed
        // TODO add your handling code here:
        
        this.updateDBFromNV();
    }//GEN-LAST:event_btnCapNhatNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        // TODO add your handling code here:
        this.deleteDBFromNV();
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        loadDBFromNV();
        this.setStatusFormNV(true);
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnmokhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmokhoaActionPerformed
        setTrangthai(true);
    }//GEN-LAST:event_btnmokhoaActionPerformed
  
    NhanVienDAO nvdao = new NhanVienDAO();
    int indexNV = 0;
    void init(){
        btnmokhoa.setVisible(false);
    }
 void loadDBFromNV() {
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        try {
            List<NhanVien> list = nvdao.select();
            for (NhanVien nhanVien : list) {
                Object[] row = {
                    nhanVien.getMaNV(), nhanVien.getTenNV(), nhanVien.getSdt(), nhanVien.getEmail(),
                    nhanVien.isVaitro() ? "Quản lý" : "Nhân viên", nhanVien.isTrangthai() ? "Hoạt Động":"Không hoạt động"
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

   

    void insertDBFromNV() {
        if(!util.checkMaNV(txtMaNV, this)){
            return;
        }
        if(!util.checkNull(txtMaNV, "Mã nhân viên", this))
        if(!check()){
            return;
        }
        NhanVien model = getModelNV();
         if(!model.getMatkhau().trim().equals(new String(txtXacNhanMK.getPassword()))){
            DialogHelper.alert(this, "Xác nhận mật khẩu chưa đúng");
            return;
        }
        try {
            nvdao.insert(model);
            this.loadDBFromNV();
            this.clearModelNV();
            DialogHelper.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Thêm mới thất bại" + e);
        }
    }

    void updateDBFromNV() {
        if(!check()){
            return;
        }
        NhanVien model = getModelNV();
     
        try {
            nvdao.update(model);
            this.loadDBFromNV();
            this.clearModelNV();
            DialogHelper.alert(this, "Cập nhật thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại");
        }
    }

    void deleteDBFromNV() {
         String manv = txtMaNV.getText();
        if(!UtilityHelper.checkXoaNhanVien(manv)){
           if( DialogHelper.confirm(this, "Bạn không thể xóa nhân viên này. Bạn có muốn vô hiệu hóa tài khoản này")){
               setTrangthai(false);
               DialogHelper.alert(this,"Vô hiệu hóa thành công");
               
               return;
            }
        }

        if (DialogHelper.confirm(this, "Bạn thực sự muốn xóa nhân viên này?")) {
           
            try {
                nvdao.delete(manv);
                this.loadDBFromNV();
                this.clearModelNV();
                DialogHelper.alert(this, "Xóa thành công!");
            } catch (Exception e) {
                DialogHelper.alert(this, "Xóa thất bại!");
            }
        }
    }

    void editDisplayNV() {
        try {
            String manv = (String) tblNhanVien.getValueAt(this.indexNV, 0);
            NhanVien model = nvdao.findById(manv);
            if (model != null) {
                this.setModelNV(model);
                this.setStatusFormNV(false);
                tblNhanVien.setRowSelectionInterval(indexNV, indexNV);
                tblNhanVien.setSelectionBackground(Color.MAGENTA);
                if(model.isTrangthai()){
                    btnmokhoa.setVisible(false);
                }else{
                     btnmokhoa.setVisible(true);
                }
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void clearModelNV() {
        this.setModelNV(new NhanVien());
        this.setStatusFormNV(true);
    }
    void setTrangthai(boolean trangthai){
        try {
            nvdao.active(this.getModelNV(), trangthai);
            this.loadDBFromNV();
        } catch (Exception e) {
            DialogHelper.alert(this, "cập nhập trạng thái thất bại");
            e.printStackTrace();
           
        }
        btnmokhoa.setVisible(!trangthai);
       
    }

    void setModelNV(NhanVien model) {
        txtMaNV.setText(model.getMaNV());
        txtTenNV.setText(model.getTenNV());
        txtSDTNV.setText(model.getSdt());
        txtEmailNV.setText(model.getEmail());
        txtPassNV.setText(model.getMatkhau());
        txtXacNhanMK.setText(model.getMatkhau());
        rdoQuanLy.setSelected(model.isVaitro());
        rdoNhanVien.setSelected(!model.isVaitro());
    }

    NhanVien getModelNV() {
        NhanVien model = new NhanVien();
        model.setMaNV(txtMaNV.getText());
        model.setTenNV(txtTenNV.getText());
        model.setSdt(txtSDTNV.getText());
        model.setEmail(txtEmailNV.getText());
        model.setMatkhau(new String(txtPassNV.getPassword()));
        model.setVaitro(rdoQuanLy.isSelected());                     
        return model;
    }

    void setStatusFormNV(boolean insertable) {
        txtMaNV.setEditable(insertable);
        btnThemNV.setEnabled(insertable);
        btnCapNhatNV.setEnabled(!insertable);
        btnXoaNV.setEnabled(!insertable);

        boolean first = this.indexNV > 0;
        boolean last = this.indexNV < tblNhanVien.getRowCount() - 1;
        btnFirstNV.setEnabled(!insertable && first);
        btnPrevNV.setEnabled(!insertable && first);
        btnNextNV.setEnabled(!insertable && last);
        btnLastNV.setEnabled(!insertable && last);
    }
    UtilityHelper util = new UtilityHelper();
     boolean check() {
        if(!util.checkNull(txtTenNV, "Tên khách hàng", this)){
            return false;
        }
       if(!util.checkName(txtTenNV, this)){
           return false;
       }
        if(!util.checkNull(txtSDTNV, "Số điện thoại nhân viên", this)){
            return false;
        }
       if(!util.checkPhone(txtSDTNV, this)){
           return false;
       }
          if(!util.checkNull(txtEmailNV, "Email khách hàng", this)){
            return false;
          }
       if(!util.checkEmail(txtEmailNV, this)){
           return false;
       }
       if(!util.checkNull(txtPassNV, "Mật Khẩu", this)){
           return false;
       }
       if(!util.checkSokitu(txtPassNV, "Mật khẩu", 8, this)){
           return false;
       }
       
       String pass = new String(txtPassNV.getPassword());
       String rePass = new String(txtXacNhanMK.getPassword());
       if(!pass.equals(rePass)){
           DialogHelper.alert(this, "Xác Nhận mật khẩu chưa đúng");
           return false;
       }
       return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatNV;
    private javax.swing.JButton btnClearNV;
    private javax.swing.JButton btnFirstNV;
    private javax.swing.JButton btnLastNV;
    private javax.swing.JButton btnNextNV;
    private javax.swing.JButton btnPrevNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JButton btnmokhoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtEmailNV;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtPassNV;
    private javax.swing.JTextField txtSDTNV;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JPasswordField txtXacNhanMK;
    // End of variables declaration//GEN-END:variables

}
