/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.PhieuNhapCTDAO;
import DAO.PhieuNhapDAO;
import DAO.SanPhamDAO;
import Helper.DateHelper;
import Helper.DialogHelper;
import Helper.ShareHelper;
import Helper.UtilityHelper;
import Model.PhieuNhap;
import Model.PhieuNhapCT;
import Model.SanPham;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DELL
 */
public class PhieuNhapFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PhieuNhapFrame
     */
    public PhieuNhapFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPhieuNhap = new javax.swing.JTabbedPane();
        tabDanhSachPhieuNhap = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtMaPN = new javax.swing.JTextField();
        txtNgayNhapPN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaNVPN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtGhiChuPN = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPhieuNhapCT = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cboSanPhamPN = new javax.swing.JComboBox<>();
        btnSuaSPPN = new javax.swing.JButton();
        btnThemSPPN = new javax.swing.JButton();
        btnXoaSPPN = new javax.swing.JButton();
        btnClearSPPN = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtSLSPPN = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtGiaNhapSPPN = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSLTonKhoPN = new javax.swing.JTextField();
        btnTimKiemSPPN = new javax.swing.JButton();
        txtTimKiemSPPN = new javax.swing.JTextField();
        btnInsertPN = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnFirstPN = new javax.swing.JButton();
        btnLastPN = new javax.swing.JButton();
        btnNextPN = new javax.swing.JButton();
        btnPrevPN = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JTextField();
        btnClearPN = new javax.swing.JButton();
        tabCapNhanPhieuNhap = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txtTimKiemPN = new javax.swing.JTextField();
        btnTimKiemPN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Quản Lý Phiếu Nhập Hàng");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tabPhieuNhap.setBackground(new java.awt.Color(255, 153, 153));
        tabPhieuNhap.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabPhieuNhapComponentShown(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin phiếu nhập"));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Mã Phiếu Nhập:");

        txtMaPN.setEditable(false);
        txtMaPN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtNgayNhapPN.setEditable(false);
        txtNgayNhapPN.setBackground(new java.awt.Color(204, 204, 204));
        txtNgayNhapPN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Ngày Nhập:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Mã Nhân Viên:");

        txtMaNVPN.setEditable(false);
        txtMaNVPN.setBackground(new java.awt.Color(204, 204, 204));
        txtMaNVPN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Ghi chú:");

        txtGhiChuPN.setColumns(20);
        txtGhiChuPN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtGhiChuPN.setRows(5);
        jScrollPane5.setViewportView(txtGhiChuPN);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaPN, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(txtMaNVPN))
                .addGap(150, 150, 150)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayNhapPN, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayNhapPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtMaNVPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản phẩm trên phiếu"));

        tblPhieuNhapCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ProductID", "Name", "Amount", "Price", "IntoMoney"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuNhapCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapCTMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPhieuNhapCT);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Tên sản phẩm: ");

        cboSanPhamPN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboSanPhamPN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSanPhamPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSanPhamPNActionPerformed(evt);
            }
        });

        btnSuaSPPN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSuaSPPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gear.png"))); // NOI18N
        btnSuaSPPN.setText("Sửa sản phẩm");
        btnSuaSPPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSPPNActionPerformed(evt);
            }
        });

        btnThemSPPN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThemSPPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThemSPPN.setText("Thêm sản phẩm");
        btnThemSPPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPPNActionPerformed(evt);
            }
        });

        btnXoaSPPN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnXoaSPPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoaSPPN.setText("Xóa sản phẩm");
        btnXoaSPPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPPNActionPerformed(evt);
            }
        });

        btnClearSPPN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClearSPPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clipboard.png"))); // NOI18N
        btnClearSPPN.setText("Làm mới");
        btnClearSPPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSPPNActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Số Lượng:");

        txtSLSPPN.setBackground(new java.awt.Color(255, 255, 255));
        txtSLSPPN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Giá Nhập:");

        txtGiaNhapSPPN.setEditable(false);
        txtGiaNhapSPPN.setBackground(new java.awt.Color(204, 204, 204));
        txtGiaNhapSPPN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("SL còn trong kho:");

        txtSLTonKhoPN.setEditable(false);
        txtSLTonKhoPN.setBackground(new java.awt.Color(204, 204, 204));
        txtSLTonKhoPN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnTimKiemSPPN.setText("Tìm Kiếm");
        btnTimKiemSPPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemSPPNActionPerformed(evt);
            }
        });

        txtTimKiemSPPN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTimKiemSPPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemSPPNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnThemSPPN)
                .addGap(103, 103, 103)
                .addComponent(btnSuaSPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaSPPN)
                .addGap(101, 101, 101)
                .addComponent(btnClearSPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(btnTimKiemSPPN))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTimKiemSPPN)
                            .addComponent(cboSanPhamPN, 0, 214, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSLSPPN)
                            .addComponent(txtGiaNhapSPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel15)
                        .addGap(27, 27, 27)
                        .addComponent(txtSLTonKhoPN, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboSanPhamPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtSLSPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtSLTonKhoPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtGiaNhapSPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTimKiemSPPN)
                            .addComponent(txtTimKiemSPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuaSPPN)
                    .addComponent(btnXoaSPPN)
                    .addComponent(btnThemSPPN)
                    .addComponent(btnClearSPPN))
                .addGap(36, 36, 36))
        );

        btnInsertPN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnInsertPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Down.png"))); // NOI18N
        btnInsertPN.setText("Tạo Phiếu Nhập");
        btnInsertPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPNActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Fax.png"))); // NOI18N
        jButton6.setText("In Phiếu Nhập");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnFirstPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1.png"))); // NOI18N
        btnFirstPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstPNActionPerformed(evt);
            }
        });

        btnLastPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2.png"))); // NOI18N
        btnLastPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastPNActionPerformed(evt);
            }
        });

        btnNextPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        btnNextPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPNActionPerformed(evt);
            }
        });

        btnPrevPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/prev.png"))); // NOI18N
        btnPrevPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevPNActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Tổng Tiền: ");

        txtTongtien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnClearPN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClearPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Text.png"))); // NOI18N
        btnClearPN.setText("Thêm Mới");
        btnClearPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabDanhSachPhieuNhapLayout = new javax.swing.GroupLayout(tabDanhSachPhieuNhap);
        tabDanhSachPhieuNhap.setLayout(tabDanhSachPhieuNhapLayout);
        tabDanhSachPhieuNhapLayout.setHorizontalGroup(
            tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDanhSachPhieuNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDanhSachPhieuNhapLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnFirstPN)
                .addGap(18, 18, 18)
                .addComponent(btnPrevPN)
                .addGap(18, 18, 18)
                .addComponent(btnNextPN)
                .addGap(18, 18, 18)
                .addComponent(btnLastPN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addGroup(tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addGroup(tabDanhSachPhieuNhapLayout.createSequentialGroup()
                        .addComponent(btnClearPN, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsertPN)))
                .addGap(18, 18, 18)
                .addGroup(tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongtien)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        tabDanhSachPhieuNhapLayout.setVerticalGroup(
            tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDanhSachPhieuNhapLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInsertPN)
                        .addComponent(jButton6)
                        .addComponent(btnClearPN))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNextPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLastPN))
                        .addGroup(tabDanhSachPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPrevPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFirstPN))))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        tabPhieuNhap.addTab("Quản lý", tabDanhSachPhieuNhap);

        tblPhieuNhap.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ PHIẾU", "MÃ NHÂN VIÊN", "NGÀY NHẬP", "GHI CHÚ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblPhieuNhap);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm Hóa Đơn"));

        txtTimKiemPN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnTimKiemPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        btnTimKiemPN.setText("Tìm Kiếm");
        btnTimKiemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemPNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtTimKiemPN, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiemPN, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemPN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemPN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabCapNhanPhieuNhapLayout = new javax.swing.GroupLayout(tabCapNhanPhieuNhap);
        tabCapNhanPhieuNhap.setLayout(tabCapNhanPhieuNhapLayout);
        tabCapNhanPhieuNhapLayout.setHorizontalGroup(
            tabCapNhanPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCapNhanPhieuNhapLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(tabCapNhanPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        tabCapNhanPhieuNhapLayout.setVerticalGroup(
            tabCapNhanPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCapNhanPhieuNhapLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPhieuNhap.addTab("Danh sách", tabCapNhanPhieuNhap);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Tạo Phiếu Nhập");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 1169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(tabPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhieuNhapCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapCTMouseClicked
        if (evt.getClickCount() == 2) {
            PhieuNhapCT model = listPN.get(tblPhieuNhapCT.getSelectedRow());
            this.editSPPN(model);

        }
    }//GEN-LAST:event_tblPhieuNhapCTMouseClicked

    private void cboSanPhamPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSanPhamPNActionPerformed
        if (cboSanPhamPN.getSelectedItem() != null) {
            selectedCBOSPPN();
        }
    }//GEN-LAST:event_cboSanPhamPNActionPerformed

    private void btnSuaSPPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSPPNActionPerformed
        updateSPPN();
    }//GEN-LAST:event_btnSuaSPPNActionPerformed

    private void btnThemSPPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPPNActionPerformed

        insertSPPN();
    }//GEN-LAST:event_btnThemSPPNActionPerformed

    private void btnXoaSPPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPPNActionPerformed
        deleteSPPN();
    }//GEN-LAST:event_btnXoaSPPNActionPerformed

    private void btnClearSPPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSPPNActionPerformed
        cleartblSPPN();
    }//GEN-LAST:event_btnClearSPPNActionPerformed

    private void btnTimKiemSPPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemSPPNActionPerformed
        loadCboSanPhamPN();
    }//GEN-LAST:event_btnTimKiemSPPNActionPerformed

    private void txtTimKiemSPPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemSPPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemSPPNActionPerformed

    private void btnInsertPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPNActionPerformed
        insertPhieuNhap();
    }//GEN-LAST:event_btnInsertPNActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        rpPhieuNhap();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnFirstPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstPNActionPerformed
        indexPN = 0;
        this.editTBLPhieuNhap();
    }//GEN-LAST:event_btnFirstPNActionPerformed

    private void btnLastPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastPNActionPerformed
        indexPN = tblPhieuNhap.getRowCount() - 1;
        this.editTBLPhieuNhap();
    }//GEN-LAST:event_btnLastPNActionPerformed

    private void btnNextPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPNActionPerformed
        indexPN++;
        this.editTBLPhieuNhap();
    }//GEN-LAST:event_btnNextPNActionPerformed

    private void btnPrevPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevPNActionPerformed
        indexPN--;
        this.editTBLPhieuNhap();
    }//GEN-LAST:event_btnPrevPNActionPerformed

    private void btnClearPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPNActionPerformed
        clearFormPN();
    }//GEN-LAST:event_btnClearPNActionPerformed

    private void tblPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapMouseClicked
        if (evt.getClickCount() == 2) {
            indexPN = tblPhieuNhap.rowAtPoint(evt.getPoint());
            if (indexPN > 0) {
                this.editTBLPhieuNhap();
                this.setStatusFormPN(false);
                tabPhieuNhap.setSelectedIndex(0);
                this.TongtienPN();
            }
        }
    }//GEN-LAST:event_tblPhieuNhapMouseClicked

    private void tabPhieuNhapComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabPhieuNhapComponentShown
        initPN();
    }//GEN-LAST:event_tabPhieuNhapComponentShown

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        initPN();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnTimKiemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemPNActionPerformed
        loadDBFormPhieuNhap();
    }//GEN-LAST:event_btnTimKiemPNActionPerformed
    int indexPN;
    PhieuNhapDAO pndao = new PhieuNhapDAO();
    PhieuNhapCTDAO pnctdao = new PhieuNhapCTDAO();
    List<PhieuNhapCT> listPN = new ArrayList<>();
    SanPhamDAO spdao = new SanPhamDAO();

    void initPN() {
        loadDBFormPhieuNhap();
        loadCboSanPhamPN();
        txtMaNVPN.setText(ShareHelper.USER.getMaNV());
        txtNgayNhapPN.setText(DateHelper.toString(new Date()));
        cboSanPhamPN.setSelectedIndex(0);
        this.sinhMaPN();
    }

    void loadDBFormPhieuNhap() {
        DefaultTableModel model = (DefaultTableModel) tblPhieuNhap.getModel();
        model.setRowCount(0);
        try {
            List<PhieuNhap> listPN = pndao.selectByKeyword(txtTimKiemPN.getText());
            for (PhieuNhap pn : listPN) {
                Object[] obj = new Object[]{pn.getMaPN(), pn.getMaNVPN(), pn.getNgayNhap(), pn.getGhiChu()};
                model.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu phiếu nhập");
        }

    }

    void loadCboSanPhamPN() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboSanPhamPN.getModel();
        model.removeAllElements();
        try {
            List<SanPham> listsp = spdao.selectByKeyword(txtTimKiemSPPN.getText());
            listsp.forEach((sp) -> {
                model.addElement(sp);
            });
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu sản phẩm");
        }

    }

    void loadTblSanPhamPN() {
        DefaultTableModel model = (DefaultTableModel) tblPhieuNhapCT.getModel();
        model.setRowCount(0);
        try {

            for (PhieuNhapCT pn : listPN) {
                SanPham sp = spdao.findById(pn.getMaSP());
                Double thanhtien = pn.getSL() * pn.getDongia();
                Object[] obj = new Object[]{pn.getMaSP(), sp.getTenSP(), pn.getSL(), pn.getDongia(), thanhtien};
                model.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu phiếu nhập");
        }

    }

    void editTBLPhieuNhap() {
        try {
            String mapn = (String) tblPhieuNhap.getValueAt(this.indexPN, 0);
            PhieuNhap modelPN = pndao.findById(mapn);
            if (modelPN != null) {
                this.setModelPN(modelPN);
                this.setStatusFormPN(false);

            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }

    }

    void setStatusFormPN(boolean is) {
        txtMaPN.setEditable(is);
        btnInsertPN.setEnabled(is);
        btnThemSPPN.setEnabled(is);
        btnSuaSPPN.setEnabled(is);
        btnXoaSPPN.setEnabled(is);
        btnClearSPPN.setEnabled(is);
        boolean first = this.indexPN > 0;
        boolean last = this.indexPN < tblPhieuNhap.getRowCount() - 1;
        btnFirstPN.setEnabled(!is && first);
        btnPrevPN.setEnabled(!is && first);
        btnNextPN.setEnabled(!is && last);
        btnLastPN.setEnabled(!is && last);
    }

    void clearFormPN() {
        txtMaPN.setText("");
        txtGhiChuPN.setText((""));
        txtSLSPPN.setText("");
        if (cboSanPhamPN.getSelectedItem() != null) {
            cboSanPhamPN.setSelectedIndex(0);
        }
        this.cleartblSPPN();
        this.setStatusFormPN(true);
        this.sinhMaPN();
    }

    void cleartblSPPN() {
        listPN = new ArrayList<>();
        loadTblSanPhamPN();
    }

    void editSPPN(PhieuNhapCT model) {
        SanPham sp = spdao.findById(model.getMaSP());
        cboSanPhamPN.getModel().setSelectedItem(sp);
        txtSLSPPN.setText(String.valueOf(model.getSL()));
        txtSLTonKhoPN.setText(String.valueOf(sp.getSoLuong()));
        txtGiaNhapSPPN.setText(String.valueOf(model.getDongia()));

    }

    PhieuNhapCT getModelSPPN() {
        PhieuNhapCT model = new PhieuNhapCT();
        model.setMaPN(txtMaPN.getText());
        model.setMaSP(((SanPham) cboSanPhamPN.getSelectedItem()).getMaSP());
        model.setSL(Integer.valueOf(txtSLSPPN.getText()));
        model.setDongia(Double.valueOf(txtGiaNhapSPPN.getText()));
        return model;
    }

    PhieuNhap getModelPN() {
        PhieuNhap pn = new PhieuNhap();
        pn.setMaPN(txtMaPN.getText().trim());
        pn.setMaNVPN(txtMaNVPN.getText().trim());
        pn.setNgayNhap(DateHelper.toDate(txtNgayNhapPN.getText()));
        pn.setGhiChu((txtGhiChuPN.getText()));
        return pn;
    }

    void setModelPN(PhieuNhap model) {
        txtMaPN.setText(model.getMaPN());
        txtMaNVPN.setText(model.getMaNVPN());
        txtNgayNhapPN.setText(DateHelper.toString(model.getNgayNhap()));
        txtGhiChuPN.setText(model.getGhiChu());
        listPN = pnctdao.findById(model.getMaPN());
        loadTblSanPhamPN();
    }

    void selectedCBOSPPN() {
        SanPham sp = (SanPham) cboSanPhamPN.getSelectedItem();

        txtGiaNhapSPPN.setText(String.valueOf(sp.getGiaNhap()));
        txtSLTonKhoPN.setText(String.valueOf(sp.getSoLuong()));

    }
    UtilityHelper util = new UtilityHelper();

    void insertSPPN() {
        if (!util.checkInt(txtSLSPPN, this, "Số lượng sản phẩm")) {
            return;
        }
        DialogHelper.alert(this, "Thêm thành công");
        PhieuNhapCT model = getModelSPPN();
        for (PhieuNhapCT pnct : listPN) {
            if (model.getMaSP().equals(pnct.getMaSP())) {
                DialogHelper.alert(this, "Sản phẩm đã có trong phiếu");
                return;
            }
        }
        listPN.add(model);
        loadTblSanPhamPN();
        TongtienPN();
    }

    void deleteSPPN() {
        if(tblPhieuNhapCT.getSelectedRow() != -1){
            listPN.remove(tblPhieuNhapCT.getSelectedRow());
        }else{
            DialogHelper.alert(this, "Bạn chưa chọn sản phẩm");
        }

        loadTblSanPhamPN();
        TongtienPN();

    }

    void updateSPPN() {
          if (!util.checkInt(txtSLSPPN, this, "Số lượng sản phẩm")) {
            return;
        }
        PhieuNhapCT model = getModelSPPN();
        if (tblPhieuNhapCT.getSelectedRow() >= 0) {
            int i = tblPhieuNhapCT.getSelectedRow();
            listPN.set(i, model);

            loadTblSanPhamPN();
            TongtienPN();
        }
    }

    void insertPhieuNhap() {
        
        if(listPN.isEmpty()){
            DialogHelper.alert(this, "Bạn chưa thêm sản phẩm trên phiếu ");
            return;
        }
        
        PhieuNhap modelpn = this.getModelPN();
        try {
            pndao.InsertPhieuNhap(modelpn);
            for (PhieuNhapCT model : listPN) {
                pnctdao.InsertPhieuNhapCT(model);
                SanPham sp = spdao.findById(model.getMaSP());
                sp.setSoLuong(sp.getSoLuong() + model.getSL());
                spdao.update(sp);

            }
            DialogHelper.alert(this, "Lưu Phiếu thành công");
            loadDBFormPhieuNhap();
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi thêm Phiếu nhập");
        }
    }

    void TongtienPN() {
        double sum = 0;
        for (int i = 0; i < tblPhieuNhapCT.getRowCount(); i++) {

            sum = sum + (double) tblPhieuNhapCT.getValueAt(i, 4);
        }
        txtTongtien.setText(String.valueOf(sum));
    }

    void sinhMaPN() {
        String mapn = "PN";
        String ngay = txtNgayNhapPN.getText().replace("/", "");
        String stt = String.valueOf(tblPhieuNhap.getRowCount() + 1);
        txtMaPN.setText(mapn + ngay + stt);
    }

    void rpPhieuNhap() {
        if(!util.checkMaPN(txtMaPN)){
            if(DialogHelper.confirm(this, "Phiếu nhập chưa được tạo bạn có muốn tạo phiếu nhập này")){
                insertPhieuNhap(); 
                return;
            }else{
                return;
            }
        }
        PhieuNhap model = this.getModelPN();
        HashMap<String, Object> hs = new HashMap<>();;
        hs.put("maphieu", model.getMaPN());
        hs.put("tennv", model.getMaNVPN());
        hs.put("ngaynhap", DateHelper.toString(model.getNgayNhap()));
        hs.put("ghichu", model.getGhiChu());
        hs.put("totalmoney", txtTongtien.getText());

        DefaultTableModel tblmodel = (DefaultTableModel) tblPhieuNhapCT.getModel();

        try {
            JasperDesign jd = JRXmlLoader.load("src\\report\\rpPhieuNhap.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jd);

            JasperPrint jp = JasperFillManager.fillReport(jr, hs, new JRTableModelDataSource(tblmodel));
            JasperViewer.viewReport(jp, true);

        } catch (JRException ex) {
            ex.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearPN;
    private javax.swing.JButton btnClearSPPN;
    private javax.swing.JButton btnFirstPN;
    private javax.swing.JButton btnInsertPN;
    private javax.swing.JButton btnLastPN;
    private javax.swing.JButton btnNextPN;
    private javax.swing.JButton btnPrevPN;
    private javax.swing.JButton btnSuaSPPN;
    private javax.swing.JButton btnThemSPPN;
    private javax.swing.JButton btnTimKiemPN;
    private javax.swing.JButton btnTimKiemSPPN;
    private javax.swing.JButton btnXoaSPPN;
    private javax.swing.JComboBox<String> cboSanPhamPN;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel tabCapNhanPhieuNhap;
    private javax.swing.JPanel tabDanhSachPhieuNhap;
    private javax.swing.JTabbedPane tabPhieuNhap;
    private javax.swing.JTable tblPhieuNhap;
    private javax.swing.JTable tblPhieuNhapCT;
    private javax.swing.JTextArea txtGhiChuPN;
    private javax.swing.JTextField txtGiaNhapSPPN;
    private javax.swing.JTextField txtMaNVPN;
    private javax.swing.JTextField txtMaPN;
    private javax.swing.JTextField txtNgayNhapPN;
    private javax.swing.JTextField txtSLSPPN;
    private javax.swing.JTextField txtSLTonKhoPN;
    private javax.swing.JTextField txtTimKiemPN;
    private javax.swing.JTextField txtTimKiemSPPN;
    private javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables
}
