/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.ThongKeDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Thongkeform extends javax.swing.JInternalFrame {

    /**
     * Creates new form Thongkeform
     */
    public Thongkeform(int i) {
        initComponents();
        tabs.setSelectedIndex(i);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongkePhieunhap = new javax.swing.JTable();
        cbxNamPN = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongkephieunhapct = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongkeBanhang = new javax.swing.JTable();
        cbxNamBH = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblThongkebanhangchitiet = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Thống Kê");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblThongkePhieunhap.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblThongkePhieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tháng", "Số lượng nhập hàng", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongkePhieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongkePhieunhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongkePhieunhap);

        cbxNamPN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbxNamPN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNamPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNamPNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Năm:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("chi tiết"));

        tblThongkephieunhapct.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblThongkephieunhapct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MASP", "Tên sản phẩm", "Sô lượng", "giá nhập thấp nhất", "giá nhập cao nhất", "Giá nhập TB"
            }
        ));
        jScrollPane2.setViewportView(tblThongkephieunhapct);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(cbxNamPN, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNamPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tabs.addTab("Nhập hàng", jPanel1);

        tblThongkeBanhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblThongkeBanhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tháng", "Số lượng bán ra ", "Tiền thu về", "khấu trừ và giảm giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongkeBanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongkeBanhangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblThongkeBanhang);

        cbxNamBH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbxNamBH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNamBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNamBHActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Năm:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("chi tiết"));

        tblThongkebanhangchitiet.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblThongkebanhangchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MASP", "Tên sản phẩm", "Sô lượng", "giá nhập thấp nhất", "giá nhập cao nhất", "Giá nhập TB"
            }
        ));
        jScrollPane4.setViewportView(tblThongkebanhangchitiet);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(cbxNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tabs.addTab("Doanh thu", jPanel2);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Thống Kê");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        init();
    }//GEN-LAST:event_formInternalFrameOpened

    private void cbxNamPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNamPNActionPerformed
        if (cbxNamPN.getSelectedItem() != null) {
            loadtblPhieunhapTK();
        }
    }//GEN-LAST:event_cbxNamPNActionPerformed

    private void tblThongkePhieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongkePhieunhapMouseClicked
        if (evt.getClickCount() == 2) {
            int month = (int) tblThongkePhieunhap.getValueAt(tblThongkePhieunhap.getSelectedRow(), 0);

            int year = Integer.valueOf(cbxNamPN.getSelectedItem().toString());

            loadtblPhieuNhapChiTietTK(year, month);
        }
    }//GEN-LAST:event_tblThongkePhieunhapMouseClicked

    private void tblThongkeBanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongkeBanhangMouseClicked
        if (evt.getClickCount() == 2) {
            int month = (int) tblThongkeBanhang.getValueAt(tblThongkeBanhang.getSelectedRow(), 0);

            int year = Integer.valueOf(cbxNamBH.getSelectedItem().toString());

            loadtblBanhHangChiTietTK(year, month);
        }
    }//GEN-LAST:event_tblThongkeBanhangMouseClicked

    private void cbxNamBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNamBHActionPerformed
        if (cbxNamBH.getSelectedItem() != null) {
            loadtblbanhangTK();
            
        }
    }//GEN-LAST:event_cbxNamBHActionPerformed
    ////////////////Fucntion///////////////////////

    void init() {
        fillCBXnamPN();
        loadtblPhieunhapTK();
        fillCBXnamBH();
        loadtblbanhangTK();
    }
    ThongKeDAO tkdao = new ThongKeDAO();

    void fillCBXnamPN() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxNamPN.getModel();
        model.removeAllElements();

        List<Object> list = tkdao.getNamPN();
        for (Object object : list) {
            model.addElement(object.toString());
        }
        cbxNamPN.setSelectedItem(0);
    }

    void loadtblPhieunhapTK() {

        DefaultTableModel model = (DefaultTableModel) tblThongkePhieunhap.getModel();
        model.setRowCount(0);
        int nam = Integer.valueOf(cbxNamPN.getSelectedItem().toString());
        List<Object[]> list = tkdao.getTTphieunhap(nam);
        for (Object[] object : list) {
            model.addRow(object);
        }
    }

    void loadtblPhieuNhapChiTietTK(int year, int month) {
        DefaultTableModel model = (DefaultTableModel) tblThongkephieunhapct.getModel();
        model.setRowCount(0);

        List<Object[]> list = tkdao.getTTphieunhapChiiet(year, month);
        for (Object[] object : list) {
            model.addRow(object);
        }

    }
    /////////////////Bán Hàng//////////////////

    void fillCBXnamBH() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxNamBH.getModel();
        model.removeAllElements();

        List<Object> list = tkdao.getNamHD();
        for (Object object : list) {
            model.addElement(object.toString());
        }
        cbxNamBH.setSelectedItem(0);
    }

    void loadtblbanhangTK() {

        DefaultTableModel model = (DefaultTableModel) tblThongkeBanhang.getModel();
        model.setRowCount(0);
        int nam = Integer.valueOf(cbxNamBH.getSelectedItem().toString());
        List<Object[]> list = tkdao.getTThoadon(nam);
        for (Object[] object : list) {
            model.addRow(object);
        }
    }

    void loadtblBanhHangChiTietTK(int year, int month) {
        DefaultTableModel model = (DefaultTableModel) tblThongkebanhangchitiet.getModel();
        model.setRowCount(0);

        List<Object[]> list = tkdao.getTThoadonChiiet(year, month);
        for (Object[] object : list) {
            model.addRow(object);
        }
    }

    ///////////////////////////

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxNamBH;
    private javax.swing.JComboBox<String> cbxNamPN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblThongkeBanhang;
    private javax.swing.JTable tblThongkePhieunhap;
    private javax.swing.JTable tblThongkebanhangchitiet;
    private javax.swing.JTable tblThongkephieunhapct;
    // End of variables declaration//GEN-END:variables
}
